Feature/mraysu/add students form
TritonSE/PIA-Program-Manager pull request #32
Opened 2024-01-18 20:05 UTC by mraysu

## Tracking Info

Resolves #8 

## Changes

Added student schema, validator, createStudent, post route

## Testing

Tested edge cases, missing fields, incorrect emails / phone numbers

## Confirmation of Change

See files in backend/src. Request bodies use following structure:
`{
"student":{ 
    "lastName":"Doe",
    "firstName":"John",
    "email":"bob@aol.com",
    "phoneNumber":"8005882300"
},
"emergency":{
    "lastName":"Doe",
    "firstName":"John",
    "email":"bob@aol.com",
    "phoneNumber":"8005882300"
},
"serviceCoordinator":{
    "lastName":"Doe",
    "firstName":"John",
    "email":"bob@aol.com",
    "phoneNumber":"8005882300"
},
"location":"HERE",
"medication":"ADVIL",
"birthday":"2023-10-01T00:00Z",
"intakeDate":"2023-10-01T00:00Z",
"tourDate":"2023-10-01T00:00Z",
"prog1":"Program 1",
"prog2":"Program 2",
"dietary":["seafood", "dairy"],
"otherString":"peanuts"
}`

2024-01-21 03:41 UTC, adhi0331 requested changes
Great Work! The comments need to be addressed before I can approve.

2024-01-21 03:41 UTC, adhi0331 commented on backend/src/app.ts
> +server.app.use("/api/student", studentRoutes);
Let's have it be "/student"

2024-01-21 03:41 UTC, adhi0331 commented on backend/src/controllers/student.ts
> +      errorHandler(new CustomError(errornum++, 400, error.msg as string), req, res);
Let's not use the CustomErrors in this way. We need to create the errors in the errors folders. See [this](https://github.com/TritonSE/ALUM-Mobile-Application/tree/main/backend/src/errors) as an example. We want to initialize the error handler like [this](https://github.com/TritonSE/ALUM-Mobile-Application/blob/main/backend/src/app.ts#L39). Store the errors in ../errors/vallidation.ts. Once this is setup properly we only need to throw that custom error.

2024-01-21 03:41 UTC, adhi0331 commented on backend/src/controllers/student.ts
> +  type typedModel = {
We should move these types outside of the route so that it can be accessed by future routes.

2024-01-22 17:16 UTC, adhi0331 approved these changes
LGTM!!! 🚀

2024-01-27 20:20 UTC, vs2961 requested changes
I get the following error when I run the backend:
![Screenshot 2024-01-27 at 12 19 17 PM](https://github.com/TritonSE/PIA-Program-Manager/assets/33765960/8135c793-998a-4309-9baa-59370e06d6c7)

It could be an error on my end, but I'm unable to verify if this works or not.

2024-01-28 07:51 UTC, aammya8 requested changes
Looks good! Works for every test case I tested except the one below (where the user types in 0000000000 as their phone number). Not sure if we want to either (1) prevent the user from typing in 0000000000 as their phone number, or (2) store it as 0000000000, instead of 0 (which is how is is being stored now)

![Screenshot 2024-01-27 at 11 47 43 PM](https://github.com/TritonSE/PIA-Program-Manager/assets/79061216/69d8e24d-0016-4811-9189-adeeae3641d8)

2024-01-28 09:48 UTC, mraysu commented
In response to @vs2961's error, I am not reproduce the error. But, I looked into possible fixes and came across common issues with error middleware. [This thread](https://github.com/ladjs/supertest/issues/416#issuecomment-514508137) proposes a simple fix by adding the fourth "next" param to the function and cites the [expressjs documentation](https://expressjs.com/ru/api.html). We can see if this fix works, and possibly apply it to Aammya's branch to address @JacobLee23's very similar error.
![image](https://github.com/TritonSE/PIA-Program-Manager/assets/96799955/a87b5371-33ca-4fa4-a89d-57916629f878)

2024-01-28 17:47 UTC, adhi0331 commented
@mraysu Victor and I were able to figure out what was causing the issue. Essentially, when you make a postman call to a route that has not been implemented (ex: localhost:4000/) then Express will call the error handler function and there error comes up. It isn't anything to do with your route. I'll resolve this bug so don't worry about it for now.

2024-01-31 20:27 UTC, aammya8 approved these changes

2024-02-01 03:09 UTC, adhi0331 approved these changes
LGTM!!!

2024-02-02 19:15 UTC, vs2961 approved these changes

2024-02-02 19:32 UTC, merged